name: Rust CI

on:
  push:
    branches: [ "main" ] # main branch
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build # build rust program
      run: cargo build --verbose
    - name: Run tests # test via cargo while keeping terminal output minimal
      run: cargo test --verbose
    - name: Image testing # use -t function built into program to test API and image display function
      run: cargo run -- -t
